# Generated by Django 4.2.27 on 2025-12-05 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolday',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
