# Generated by Django 4.2.27 on 2025-12-05 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_schoolday_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='tracking_mode',
            field=models.CharField(choices=[('attendance', 'Attendance Only'), ('subjects', 'Subjects')], default='attendance', max_length=20),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.student')),
            ],
        ),
        migrations.AddField(
            model_name='schoolday',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='school_days', to='core.subject'),
        ),
    ]
