# Generated by Django 4.2.27 on 2025-12-06 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_student_tracking_mode_subject_schoolday_subjects'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schoolday',
            unique_together={('student', 'date')},
        ),
    ]
