# Generated by Django 4.2.27 on 2025-12-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_schoolday_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolday',
            name='subjects_completed',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
