# Generated by Django 4.2.27 on 2025-12-06 16:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_schoolday_subjects_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('date_uploaded', models.DateField(default=django.utils.timezone.now)),
                ('file', models.FileField(upload_to='samples/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_samples', to='core.student')),
            ],
        ),
    ]
