# Generated by Django 4.2.27 on 2025-12-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_worksample'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_year_end',
            field=models.DateField(blank=True, help_text='End date of the academic year', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='academic_year_start',
            field=models.DateField(blank=True, help_text='Start date of the academic year', null=True),
        ),
    ]
