# Generated by Django 4.2.27 on 2025-12-07 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_student_academic_year_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('director_name', models.CharField(max_length=100)),
                ('required_days', models.PositiveIntegerField(default=180)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='association_logos/')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.association'),
        ),
    ]
