# Generated by Django 4.2.27 on 2025-12-07 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_association_student_association'),
    ]


def create_default_association(apps, schema_editor):
    Association = apps.get_model('core', 'Association')
    Student = apps.get_model('core', 'Student')
    
    # Create default association
    default_assoc, created = Association.objects.get_or_create(
        name='Palmetto Digital Association',
        defaults={
            'director_name': 'Unknown',  # Placeholder as not specified
            'required_days': 180
        }
    )
    
    # Assign to all existing students
    Student.objects.update(association=default_assoc)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_association_student_association'),
    ]

    operations = [
        migrations.RunPython(create_default_association),
    ]
