# Generated by Django 4.2.27 on 2025-12-07 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_familyprofile'),
    ]


def backfill_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    FamilyProfile = apps.get_model('core', 'FamilyProfile')
    Student = apps.get_model('core', 'Student')
    
    for user in User.objects.all():
        profile, created = FamilyProfile.objects.get_or_create(user=user)
        
        # Check if any student has an association
        student = Student.objects.filter(user=user, association__isnull=False).first()
        if student and student.association:
            profile.association = student.association
            profile.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_familyprofile'),
    ]

    operations = [
        migrations.RunPython(backfill_profiles),
    ]
