# Generated by Django 4.2.27 on 2025-12-07 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20251207_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='association',
        ),
    ]
