# Generated by Django 4.2.27 on 2025-12-07 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_migrate_json_subjects_to_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolday',
            name='subjects_completed',
        ),
    ]
