# Generated by Django 4.2.27 on 2025-12-07 23:20

from django.db import migrations


def seed_global_subjects(apps, schema_editor):
    """Seed GlobalSubject records and link existing Subject records."""
    GlobalSubject = apps.get_model('core', 'GlobalSubject')
    Subject = apps.get_model('core', 'Subject')
    
    # Create standard subjects
    subjects = [
        'Math', 'Science', 'Reading', 'Writing', 'Social Studies',
        'History', 'Literature', 'Composition', 'Art', 'Music', 'PE'
    ]
    
    for name in subjects:
        GlobalSubject.objects.get_or_create(name=name)
    
    # Link existing Subject records to GlobalSubject (case-insensitive match)
    for subject in Subject.objects.all():
        if subject.name:
            match = GlobalSubject.objects.filter(name__iexact=subject.name).first()
            if match:
                subject.global_subject = match
                subject.name = None
                subject.save()


def reverse_seed(apps, schema_editor):
    """Reverse migration: restore custom names from global subjects."""
    Subject = apps.get_model('core', 'Subject')
    
    for subject in Subject.objects.filter(global_subject__isnull=False, name__isnull=True):
        subject.name = subject.global_subject.name
        subject.global_subject = None
        subject.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_global_subject_architecture'),
    ]

    operations = [
        migrations.RunPython(seed_global_subjects, reverse_seed),
    ]
