# Generated by Django 4.2.27 on 2025-12-08 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_seed_global_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='tracking_mode',
        ),
    ]
