# Generated by Django 4.2.27 on 2025-12-10 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grading_system',
            field=models.CharField(choices=[('quarters', 'Quarters'), ('semesters', 'Semesters')], default='quarters', max_length=20),
        ),
        migrations.AlterField(
            model_name='grade',
            name='term',
            field=models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4'), ('S1', 'Semester 1'), ('S2', 'Semester 2')], max_length=2),
        ),
    ]
