# Generated by Django 4.2.27 on 2025-12-11 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_student_grading_system_alter_grade_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='term',
            field=models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4'), ('Fall', 'Fall'), ('Spring', 'Spring')], max_length=10),
        ),
    ]
