# Generated by Django 4.2.27 on 2025-12-11 02:30

import logging
from django.db import migrations

logger = logging.getLogger(__name__)

def update_semester_labels(apps, schema_editor):
    Grade = apps.get_model('core', 'Grade')
    
    # Update S1 -> Fall
    updated_s1 = Grade.objects.filter(term='S1').update(term='Fall')
    logger.info(f"Updated {updated_s1} S1 grades to Fall")
    print(f"Updated {updated_s1} S1 grades to Fall")

    # Update S2 -> Spring
    updated_s2 = Grade.objects.filter(term='S2').update(term='Spring')
    logger.info(f"Updated {updated_s2} S2 grades to Spring")
    print(f"Updated {updated_s2} S2 grades to Spring")

def reverse_semester_labels(apps, schema_editor):
    Grade = apps.get_model('core', 'Grade')
    
    # Update Fall -> S1
    updated_fall = Grade.objects.filter(term='Fall').update(term='S1')
    logger.info(f"Reversed {updated_fall} Fall grades to S1")

    # Update Spring -> S2
    updated_spring = Grade.objects.filter(term='Spring').update(term='S2')
    logger.info(f"Reversed {updated_spring} Spring grades to S2")

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_grade_term'),
    ]

    operations = [
        migrations.RunPython(update_semester_labels, reverse_semester_labels),
    ]
